# Workflow for testing code and submitting codecov report
name: Build, Test, and Coverage Report

on:
  # Triggers the workflow on push or pull request events
  pull_request:
    types: [opened, synchronize]
    
jobs:
  build:
    #run project on latest ubuntu
    runs-on: ubuntu-latest
    
    environment: test
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Kotlin Linter
        uses: vroy/gha-kotlin-linter@v1
      
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Build Gradle
        run: gradle build

      - name: Run Tests
        run: gradle test
    
